ai:
  enabled: true
  model: gpt-3.5-turbo
  offsite: false
  provider: openai
project:
  created: /Users/romanshubin/Documents/dae_6_month/CLI_tool
  name: test-project
  scope_file: null
safety:
  excluded_networks:
  - 127.0.0.0/8
  - 10.0.0.0/8
  scope_check: true
tools:
  nmap:
    default_flags: -sS -sV -O
  theharvester:
    default_limit: 100
    default_source: google
